
["Rings of Ascension"]
	#The cooldown in seconds of the Ring of Undying
	#Range: > 0
	ringUndyingCooldown = 600
	#The amount of hearts that Max Health's ring gives you.
	#Range: 0 ~ 400
	ringHealthHearts = 3

["Enable/Disable Rings"]
	ringFireResistance = true
	ringInvisibility = true
	ringRegeneration = true
	ringSlowFalling = true
	ringStrength = true
	ringWaterBreathing = true
	ringSpeed = true
	ringNightVision = true
	ringJumpBoost = true
	ringMining = true
	ringLuck = true
	ringDolphin = true
	ringMagnetism = true
	ringFlight = false
	ringPoisonResistance = true
	ringHungerless = false
	ringGrowth = true
	ringKnockbackResistance = true
	ringHealth = true
	ringSponge = true
	ringExperience = true
	ringWaterWalking = true
	ringWither = true
	ringUndying = false
	ringSlowResistance = true

["Rings Amplifier"]

	#Sets the amplifier of the effect given by the ring. Example:
	#0 = Fire Resistance I
	#1 = Fire Resistance II
	["Rings Amplifier".Amplifiers]
		#Range: 0 ~ 255
		ringAmplifierFireResistance = 1
		#Range: 0 ~ 255
		ringAmplifierInvisibility = 0
		#Range: 0 ~ 255
		ringAmplifierRegeneration = 0
		#Range: 0 ~ 255
		ringAmplifierSlowFalling = 0
		#Range: 0 ~ 255
		ringAmplifierStrength = 0
		#Range: 0 ~ 255
		ringAmplifierWaterBreathing = 1
		#Range: 0 ~ 255
		ringAmplifierSpeed = 0
		#Range: 0 ~ 255
		ringAmplifierNightVision = 0
		#Range: 0 ~ 255
		ringAmplifierJumpBoost = 0
		#Range: 0 ~ 255
		ringAmplifierMining = 1
		#Range: 0 ~ 255
		ringAmplifierLuck = 1
		#Range: 0 ~ 255
		ringAmplifierDolphin = 0

